server:
  port: 8095

spring:
  application:
    name: studyroom-reservation

  datasource:
    url: jdbc:mysql://localhost:8625/studyroom_reservation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: gnalzk9310!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    
jwt:
  secret: "studyroom-reservation-local-jwt-secret-key-must-be-at-least-32-bytes"
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs